### ISSUE TITLE
没有网

### ISSUE THREAD

**Issue by linkway321** [DiZhou92/ROG-STRIX-Z490-G-WIFI-ASUS#1]
以太网和WIFI都没有
系统版本：11.2

**Comment by chaodyz** [comment]
目前我的build是10.15.5，没有这方面的问题 
你说的问题可能是有的，bigsur不太稳定，我暂时不会去尝试

建议你以这个为蓝本按照教程走一遍， 可能是SMBIOS 需要更新到iMac20,1
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#starting-point
